/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autobazargui;

import data.Car;
import data.ServiceBook;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author lmasic
 */
public class AutobazarGUI extends javax.swing.JFrame {

    /**
     * Creates new form hlavni
     */
    public AutobazarGUI() {
        initComponents();
        loadListOfCars();
        loadServiceBook();
    }

    public void generateCars() {
        data.Cars.init();
    }
    public int selectedIndex;

    public void loadListOfCars() {

        ArrayList<Car> cl = data.Cars.getCarsList();
        DefaultListModel model = new DefaultListModel();

        for (int i = 0; i < cl.size(); i++) {
            model.add(i, cl.get(i));
        }

        CarList.setModel(model);
        CarList.repaint();

    }

    public void loadServiceBook() {

        if (selectedIndex >= 0) {
            if (data.Cars.getCarsList().size() > selectedIndex) {
                List<String> book = data.Cars.getCarsList().get(selectedIndex).serviceBook.getServiceRecords();
                DefaultListModel model = new DefaultListModel();

                for (int i = 0; i < book.size(); i++) {
                    model.add(i, book.get(i));
                }
                BookList.setModel(model);
                BookList.repaint();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        znackaL = new javax.swing.JLabel();
        brandInput = new javax.swing.JTextField();
        znackaL1 = new javax.swing.JLabel();
        modelInput = new javax.swing.JTextField();
        znackaL2 = new javax.swing.JLabel();
        mileageInput = new javax.swing.JTextField();
        znackaL3 = new javax.swing.JLabel();
        consumptionInput = new javax.swing.JTextField();
        priceInput = new javax.swing.JTextField();
        znackaL4 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        znackaL.setText("Značka");

        znackaL1.setText("Model");

        znackaL2.setText("Najeto");

        znackaL3.setText("Spotřeba");

        znackaL4.setText("Cena");

        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBtnMouseClicked(evt);
            }
        });

        CarList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CarList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CarList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(znackaL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brandInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(znackaL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(znackaL2)
                            .addGap(18, 18, 18)
                            .addComponent(mileageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(znackaL4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(znackaL3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(consumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createBtn)
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znackaL)
                    .addComponent(brandInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znackaL1)
                    .addComponent(modelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znackaL2)
                    .addComponent(mileageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znackaL3)
                    .addComponent(consumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znackaL4)
                    .addComponent(priceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(createBtn))
                .addGap(20, 20, 20))
        );

        BookList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        BookList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(BookList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void CarListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarListMouseClicked
        int index = CarList.getSelectedIndex();
        selectedIndex = index;
        //String s = (String) CarList.getSelectedValue();

        brandInput.setText(data.Cars.getCarsList().get(index).getZnacka());
        modelInput.setText(data.Cars.getCarsList().get(index).getModel());
        mileageInput.setText(String.valueOf(data.Cars.getCarsList().get(index).getNajeto()));
        consumptionInput.setText(String.valueOf(data.Cars.getCarsList().get(index).getSpotreba()));
        priceInput.setText(String.valueOf(data.Cars.getCarsList().get(index).getCena()));
        loadServiceBook();
    }//GEN-LAST:event_CarListMouseClicked


    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        int index = selectedIndex;
        //System.out.println(index);
        data.Cars.getCarsList().get(index).setZnacka(brandInput.getText());
        data.Cars.getCarsList().get(index).setModel(modelInput.getText());
        data.Cars.getCarsList().get(index).setNajeto(Integer.parseInt(mileageInput.getText()));
        data.Cars.getCarsList().get(index).setSpotreba(Double.parseDouble(consumptionInput.getText()));
        data.Cars.getCarsList().get(index).setCena(Double.parseDouble(priceInput.getText()));
        loadListOfCars();
        loadServiceBook();

    }//GEN-LAST:event_saveBtnMouseClicked

    private void createBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseClicked
        // TODO add your handling code here:
        Car car = null;
        try {
            car = new Car(brandInput.getText(), modelInput.getText(), Integer.parseInt(mileageInput.getText()), Double.parseDouble(consumptionInput.getText()), Double.parseDouble(priceInput.getText()));
            car.serviceBook = new ServiceBook(car);
            car.serviceBook.addRecord("Prvni rekord k "+brandInput.getText());
            car.serviceBook.addRecord("Druhy rekord k "+brandInput.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
        ArrayList<Car> cl = data.Cars.getCarsList();
        cl.add(car);
        System.out.println(cl);
        loadListOfCars();
        loadServiceBook();
    }//GEN-LAST:event_createBtnMouseClicked

    private void BookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BookListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutobazarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutobazarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutobazarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutobazarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutobazarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> BookList;
    private javax.swing.JList<String> CarList;
    private javax.swing.JTextField brandInput;
    private javax.swing.JTextField consumptionInput;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mileageInput;
    private javax.swing.JTextField modelInput;
    private javax.swing.JTextField priceInput;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel znackaL;
    private javax.swing.JLabel znackaL1;
    private javax.swing.JLabel znackaL2;
    private javax.swing.JLabel znackaL3;
    private javax.swing.JLabel znackaL4;
    // End of variables declaration//GEN-END:variables
}
